name: Test, Build and Release

on:
  push:
    tags:
      - 'v*'

env:
  CARGO_TERM_COLOR: always

jobs:
  release:
    permissions:
      contents: write

    runs-on: windows-latest

    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v6

      - name: Run Tests
        run: cargo test --verbose

      - name: Build Release
        run: cargo build --release --verbose

      - name: Publish GitHub Release
        uses: softprops/action-gh-release@v3
        with:
          files: target/release/d3d11.dll
